### ISSUE TITLE
0.1.6 release failed to build with go 1.21.0

### ISSUE THREAD

**Issue by chenrui333** [smmr-software/mabel#15]
Looks like 0.1.6 release does not build with go1.21.0, see the error log as below:

```
# github.com/anacrolix/go-libutp
/Users/rui/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:16:10: cannot define new methods on non-local type *C.utp_callback_arguments
/Users/rui/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:24:10: cannot define new methods on non-local type *C.utp_callback_arguments
/Users/rui/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:28:10: cannot define new methods on non-local type *C.utp_callback_arguments
/Users/rui/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:32:10: cannot define new methods on non-local type *C.utp_callback_arguments
/Users/rui/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:36:10: cannot define new methods on non-local type *C.utp_callback_arguments
/Users/rui/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/utp.go:29:12: cannot define new methods on non-local type *C.utp_context
/Users/rui/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/utp.go:40:12: cannot define new methods on non-local type *C.utp_context
```

relates to https://github.com/Homebrew/homebrew-core/pull/134468

**Comment by anacrolix** [comment]
There's a fix if you run `go get github.com/anacrolix/go-libutp@v1.3.1`. It might also have been pulled into some upstream modules like anacrolix/torrent.

**Comment by chenrui333** [comment]
> There's a fix if you run `go get github.com/anacrolix/go-libutp@v1.3.1`. It might also have been pulled into some upstream modules like anacrolix/torrent.

should this dependency update be incorporated into the go.mod?

**Comment by anacrolix** [comment]
Running that command should update the `// indirect` dependency in go.mod, assuming you are not using go-libutp directly from your module.

**Comment by anacrolix** [comment]
This one: https://github.com/smmr-software/mabel/blob/4b594b8adb589c466c1fad661016792ef07a1408/go.mod#L28C4-L28C4.

**Comment by FIGBERT** [comment]
Also going to use this issue to briefly apologize for my general inactivity here. I hope to get back to working on this in my spare time eventually, I really like the project. Just very busy as of late :)
