### ISSUE TITLE
Exceding size

### ISSUE THREAD

**Issue by arobase-che** [smmr-software/mabel#4]
Hello \o

I'm trying to install this tool with : `go install github.com/smmr-software/mabel@latest` (i also tried to fix the version to v0.1.0).

And it doesn't worked.

tl;dr: You should update `crawshaw.io/sqlite` as soon as they release a new version, they haven't yet.

I get : 
```sh
$ go install github.com/smmr-software/mabel@latest
# crawshaw.io/sqlite
Dans le fichier inclus depuis .go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20210127221821-98b1f83c5508/static.go:19:
.go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20210127221821-98b1f83c5508/./c/sqlite3.c: Dans la fonction « sqlite3Fts5IndexQuery »:
.go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20210127221821-98b1f83c5508/./c/sqlite3.c:220863:18: attention: « memcpy » la limite spécifiée 18446744073709551615 excède la taille maximale 9223372036854775807 de l'objet [-Wstringop-overflow=]
220863 |     if( nToken ) memcpy(&buf.p[1], pToken, nToken);
       |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I don't know why it's in french (Go doesn't use my locale ?)  but it's basically a -1 that convert to 2^64 - 1 in unsigned type and so the size if too big fr memcpy for what ever reason.

I don't think that a the problem comes from this repo but crawshaw.io/sqlite  seems to have fixed that issue yesterday.

https://github.com/crawshaw/sqlite/pull/135

You should update as soon as they release a new version. You can't do anything sooner.
Bye \o

**Comment by taylorlanglopez** [comment]
Same type of issue for me. Also having an error within crawshaw.io/sqlite

![image](https://user-images.githubusercontent.com/17031890/174661700-2e36dc6b-89eb-4ca8-9554-b19384970f9d.png)

**Comment by mindhuntr** [comment]
I have encountered the same error as well 

![2022-06-21_09-48](https://user-images.githubusercontent.com/107744570/174715352-564f3d6f-9573-46c9-b89e-fcdda6d38913.png)

**Comment by arobase-che** [comment]
Thank you for you report too. I'm pretty sure we are numerous to encounter that error.

Until a new release from crawshaw.io/sqlite, the maintainers can't do anything about this issue. Maybe we shouldn't post any more to not monopolize maintainers attention.

**Comment by art3misxmoon** [comment]
yep, we'll update our dependencies when there's a new version. thanks for letting us know, though!

**Comment by usrme** [comment]
Maybe I'm letting my ignorance show too much here, but why can't the indirect dependency just be updated with something like `go get crawshaw.io/sqlite@4172234090bc093594a3d9443df2ea289b0c2f6c`? After doing that I was able to build the project just fine :thinking:

**Comment by FIGBERT** [comment]
Just updated all dependencies, including `crawshaw.io/sqlite` to its most recent commit (per @usrme's suggestion). Would love if everybody here could try out the most recent version and let us know if everything is working for y'all.

**Comment by arobase-che** [comment]
👌

```sh
$ go install ***@***.***
```

Works like a charm.
