### ISSUE TITLE
What the full options for the config file?

### ISSUE THREAD

**Issue by anarchy89** [smmr-software/mabel#5]
Is there a place with the full options available for the config file, I want to randomise the port on startup and I want to enable encryption. Is that possible?

**Comment by ovitente** [comment]
Sure, you can find all fields here https://github.com/smmr-software/mabel/blob/268bec0fe7156235aa6aa81e180e831a04797ef6/config.go#L15 )

**Comment by FIGBERT** [comment]
The full options for the config file are enumerated in the `README.md` [config section](https://github.com/smmr-software/mabel#config-file).

> I want to randomise the port on startup

You cannot do this through the config, as it is a static `.toml` file. If you really want this I would recommend aliasing `mabel` to something like `mabel -p $(gen_random _port)`.

> I want to enable encryption

I'm not sure I understand what you mean...

**Comment by anarchy89** [comment]
thanks for the response @FIGBERT. When you look at apps like vuze and tixati, they have an option to prefer encrypted connections. https://support.tixati.com/settings%20-%20network%20-%20connections. Can this be done?

**Comment by FIGBERT** [comment]
Appreciate the clarification. We use [anacrolix/torrent](https://github.com/anacrolix/torrent) as our torrent library – we currently use the libraries default policy, which I'm accepts encrypted *and* unencrypted peer connections.

However, after some research, it looks like [this is configurable](https://godocs.io/github.com/anacrolix/torrent#HeaderObfuscationPolicy). We'll get to work exposing this to the users via the config.

**Comment by FIGBERT** [comment]
It looks like `anacrolix/torrent` (and thus `mabel`) prefers encrypted clients [by default](https://github.com/anacrolix/torrent/blob/eeb021b134137d2096f0ef899d5215ece8989ba0/config.go#L195-L198).

Is there interest in a config option to prevent unencrypted connections altogether?
