### ISSUE TITLE
Pasting a HTTP address into torrent field panics

### ISSUE THREAD

**Issue by bronikowski** [smmr-software/mabel#6]
Build it on an x86 laptop for a test drive, pasted a http://adress/of/file.torrent, it went panic. The encoding suggests it does not expect that kind of source.

```
encoding/hex: invalid byte: U+0068 'h'

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /home/emil/.asdf/installs/golang/1.18.1/go/src/runtime/debug/stack.go:24 +0x83
runtime/debug.PrintStack()
        /home/emil/.asdf/installs/golang/1.18.1/go/src/runtime/debug/stack.go:16 +0x1a
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
        /home/emil/.asdf/installs/golang/1.18.1/packages/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:371 +0xc0
panic({0x87f1100, 0x8e17160})
        /home/emil/.asdf/installs/golang/1.18.1/go/src/runtime/panic.go:844 +0x223
github.com/anacrolix/torrent/metainfo.NewHashFromHex(...)
        /home/emil/.asdf/installs/golang/1.18.1/packages/pkg/mod/github.com/anacrolix/torrent@v1.44.0/metainfo/hash.go:70
github.com/smmr-software/mabel/internal/torrent.addInfoHash(0xa36929c, 0xa369080, 0x9d4c2c0, 0x9d62480, 0x8df8ac0)
        /tmp/mabel/internal/torrent/infohash.go:25 +0x30a
github.com/smmr-software/mabel/internal/torrent.AddTorrent(0xa36929c, 0xa3692a4, 0x9d4c2c0, 0x9d62480, 0x8df8ac0)
        /tmp/mabel/internal/torrent/torrent.go:49 +0xd4
github.com/smmr-software/mabel/full.addTorrent.Update({0x7d, 0x27, 0x1, {{0x0, 0x0}, {0x889a3c4, 0x2}, {0x0, 0x0}, 0x1f972880, ...}, ...}, ...)
        /tmp/mabel/full/add_torrent.go:57 +0xbd2
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0x9d1c000)
        /home/emil/.asdf/installs/golang/1.18.1/packages/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:538 +0x1058
github.com/charmbracelet/bubbletea.(*Program).Start(...)
        /home/emil/.asdf/installs/golang/1.18.1/packages/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:547
github.com/smmr-software/mabel/full.Execute(0x9e34710, 0x9d98fc8, 0x9e2caa0, 0x9e2caa9, 0x8df8ac0)
        /tmp/mabel/full/main.go:33 +0xea
main.main()
        /tmp/mabel/main.go:134 +0x82f
```

**Comment by usrme** [comment]
@FIGBERT, @art3misxmoon, would you mind if I tackle this? I'm a budding Go developer and would love to try my hand at something more real than what I've currently been working on.

**Comment by bronikowski** [comment]
> @FIGBERT, @art3misxmoon, would you mind if I tackle this? I'm a budding Go developer and would love to try my hand at something more real than what I've currently been working on.

Feel free to ping me if you want it test driven. :-)

**Comment by bronikowski** [comment]
> @bronikowski, I'm unable to replicate this on an x64 machine, which may not be surprising. I am, however, getting a "Error open : no such file or directory" when inputting a link to a torrent file myself.

I don't have x64 handy, but I could build it on two different ARM cpus and see how it fares.

**Comment by FIGBERT** [comment]
@usrme any progress here? I would be willing to take over, but don't want to jump in too early if you're cooking something up...

**Comment by usrme** [comment]
@FIGBERT, I'm still, of course, interested in doing this, but at the moment I'm short on time to tackle this. I'm terribly sorry for not letting you know sooner and that this has perhaps dragged on longer than it would have otherwise.

**Comment by FIGBERT** [comment]
@usrme no worries at all. I am currently short on time as well - if you happen to get to it before us, just let us know here. If I start working on this, I'll ping everybody as well.
